### ISSUE TITLE
GET Payload

### ISSUE THREAD

**Issue by aamfahrur** [namdevel/DuniaGames#1]
Halo agan, saya menggunakan Class ini untuk kebutuhan panel saya, terima kasih, namun saya ingin menambahkan beberapa game lain dan saya bingung cara mendapatkan payloadnya.

**Comment by namtxs** [comment]
sertakan saja list game nya, nanti saya tambah

**Comment by aamfahrur** [comment]
Ragnarok
Mobile Legends
Arena of Valor
CrisisAction
Speed Drifters
HAGO
Free Fire
Call of Duty Mobile
Life After
PUBG Mobile
PUBG Mobile Lite
ChessRush
Point Blank
Light of Thel
Valorant
Lords Mobile
Dragon Raja
Laplace M

**Comment by CreyziFx** [comment]
Kak Coba Dong Di Buatin Vidio Untuk Api Duniagames Nya Biyar Saya Paham Cara Mengunakan Nya
